### ISSUE TITLE
Use electric purple as primary color?

### ISSUE THREAD

**Issue by tabacitu** [DigitallyHappy/BackStrap#56]
I think it looks much better than the standard blue.

https://demo.backpackforlaravel.com/admin/login

Right now this overlay is added online inside the Backpack demo, but I think maybe we should make it the default color in Backstrap?

**Comment by tabacitu** [comment]
@pxpm what do you think - do you like the purple better than the blue?

**Comment by pxpm** [comment]
@tabacitu I like the electric purple color scheme, and to be inline with what we show in demo to the users I think it's the best option to have it enabled by default. 
Atleast, if I saw demo and download backpack I am not expecting to have a different color scheme than the demo.
